name = "my-worker"
routes = [
  { pattern = "whosonpole.org", zone_name = "whosonpole.org" },
]
assets = { directory = "public" }

[env.dev]
name = "my-dev-worker"
routes = [
  { pattern = "dev.whosonpole.org", zone_name = "whosonpole.org" },
]